# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x02nm\" \n\x07Vector2\x12\t\n\x01y\x18\x01 \x01(\x01\x12\n\n\x02\x64y\x18\x02 \x01(\x01\"t\n\x0cRequirements\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12 \n\x0bhomo_cauchy\x18\x03 \x01(\x0b\x32\x0b.nm.Vector2\x12\x1b\n\x06\x63\x61uchy\x18\x04 \x01(\x0b\x32\x0b.nm.Vector2\x12\x0f\n\x07\x65psilon\x18\x05 \x01(\x01\"t\n\x11RequirementsConst\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12 \n\x0bhomo_cauchy\x18\x03 \x01(\x0b\x32\x0b.nm.Vector2\x12\x1b\n\x06\x63\x61uchy\x18\x04 \x01(\x0b\x32\x0b.nm.Vector2\x12\n\n\x02h0\x18\x05 \x01(\x01\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"$\n\x07TabFunc\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.nm.Point\"4\n\x0cTabFuncWithH\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.nm.Point\x12\t\n\x01h\x18\x02 \x03(\x01\x32\x7f\n\x10\x45valuateBoundary\x12\x37\n\rEvaluateConst\x12\x15.nm.RequirementsConst\x1a\x0b.nm.TabFunc(\x01\x30\x01\x12\x32\n\x08\x45valuate\x12\x10.nm.Requirements\x1a\x10.nm.TabFuncWithH(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTOR2']._serialized_start=18
  _globals['_VECTOR2']._serialized_end=50
  _globals['_REQUIREMENTS']._serialized_start=52
  _globals['_REQUIREMENTS']._serialized_end=168
  _globals['_REQUIREMENTSCONST']._serialized_start=170
  _globals['_REQUIREMENTSCONST']._serialized_end=286
  _globals['_POINT']._serialized_start=288
  _globals['_POINT']._serialized_end=317
  _globals['_TABFUNC']._serialized_start=319
  _globals['_TABFUNC']._serialized_end=355
  _globals['_TABFUNCWITHH']._serialized_start=357
  _globals['_TABFUNCWITHH']._serialized_end=409
  _globals['_EVALUATEBOUNDARY']._serialized_start=411
  _globals['_EVALUATEBOUNDARY']._serialized_end=538
# @@protoc_insertion_point(module_scope)
