# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_files/main.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15grpc_files/main.proto\x12\x02nm\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"7\n\x07TabFunc\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.nm.Point\x12\x11\n\texpand_to\x18\x02 \x01(\x03\"*\n\x08TabFuncs\x12\x1e\n\ttab_funcs\x18\x01 \x03(\x0b\x32\x0b.nm.TabFunc\"C\n\x06Spline\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.nm.Point\x12\x1e\n\x0b\x62\x61se_points\x18\x02 \x03(\x0b\x32\t.nm.Point27\n\rComputeSpline\x12&\n\x08\x45valuate\x12\x0c.nm.TabFuncs\x1a\n.nm.Spline0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_files.main_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=29
  _globals['_POINT']._serialized_end=58
  _globals['_TABFUNC']._serialized_start=60
  _globals['_TABFUNC']._serialized_end=115
  _globals['_TABFUNCS']._serialized_start=117
  _globals['_TABFUNCS']._serialized_end=159
  _globals['_SPLINE']._serialized_start=161
  _globals['_SPLINE']._serialized_end=228
  _globals['_COMPUTESPLINE']._serialized_start=230
  _globals['_COMPUTESPLINE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
